DROP TABLE IF EXISTS QUOTES;

CREATE TABLE QUOTES (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  BID DECIMAL(16, 8),
  ASK DECIMAL(16, 8),
  EXCHANGE VARCHAR(250) NOT NULL,
  NAME VARCHAR(250) NOT NULL
);